/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.hbsgui;

import hbs.Customer;
import hbs.DatePair;
import hbs.HBS;
import hbs.Location;
import hbs.Room;
import hbs.RoomType;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 * ShowHistory GUI, show all reservation and could choose cancel a selected one
 * @author Shuo Zhang <shuozhang2014@u.northwestern.edu>
 */
public class ShowHistory extends javax.swing.JFrame {
	
	private ArrayList<Customer> customerList;
	private ArrayList<Location> locationList;
	private Customer cus;
	
	public void update() {
		String[] resArray = new String[cus.getReservationList().size()];
		for (int i = 0; i < resArray.length; i++) {
			resArray[i] = new String("ID: " + cus.getReservationList().get(i).getIDNumber());
		}
		
		Object[][] rows = new Object[resArray.length][];
		
		for (int i = 0; i < resArray.length; i++) {	
			rows[i] = new Object[9];
			
			rows[i][0] = (Object) new Integer(cus.getReservationList().get(i).getIDNumber());
			rows[i][1] = (Object) new String(cus.getReservationList().get(i).getLocation().getCity());
			rows[i][2] = (Object) new String(cus.getReservationList().get(i).getChosenHotel().getHotelName());
			
			switch (cus.getReservationList().get(i).getChosenRoom().get(0).getType()) {
				case SINGLE:
					rows[i][3] = (Object) new String("SINGLE");
					break;
				case DOUBLE:
					rows[i][3] = (Object) new String("DOUBLE");
					break;
				case JUNIORSUITE:
					rows[i][3] = (Object) new String("JUNIORSUITE");
					break;
				default:
					break;
			}
			
			rows[i][4] = (Object) new Integer(cus.getReservationList().get(i).getChosenRoom().size());
			rows[i][5] = (Object) new Double(cus.getReservationList().get(i).getTotalCost());
			rows[i][6] = (Object) new String(cus.getReservationList().get(i).getBookDate().toString());
			rows[i][7] = (Object) new String(cus.getReservationList().get(i).getChosenDate().getCheckInDate().toString());
			rows[i][8] = (Object) new String(cus.getReservationList().get(i).getChosenDate().getCheckOutDate().toString());
		}
		
		final Object headers[] = {"reservation ID", "location", "hotel name", "room type", 
			"num of rooms", "total cost", "booking date", "check-in date", "check-out date"};
		
		jTable2.setModel(new javax.swing.table.DefaultTableModel(rows, headers));
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(resArray));
	}
    
	/**
	 * The constructor of ShowHistory GUI
	 * @param locationList a list of locations
	 * @param customerList a list of customers
	 * @param cus current customer
	 */
    public ShowHistory(ArrayList<Location> locationList, ArrayList<Customer> customerList,
			Customer cus) {
        this.locationList = locationList;
		this.customerList = customerList;
		this.cus = cus;
		
		initComponents();
		
		update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservation History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 24))); // NOI18N

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Quit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * Save states and quit the program
	 * @param evt click button
	 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HBS.writeLocationList("locationDB.dat", locationList);
        HBS.writeCustomerList("customerDB.dat", customerList);
        System.exit(0);

    }//GEN-LAST:event_jButton2ActionPerformed
	
	/**
	 * Cancel a selected reservation
	 * @param evt click button
	 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
		int reservationIndex = jComboBox1.getSelectedIndex();
		cus.cancel(cus.getReservationList().get(reservationIndex).getIDNumber());
		update();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
